name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
        run: npx semantic-release